# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
$RNFirebaseAsStaticFramework = true

target 'DonationApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # Pods for DonationApp

  target 'DonationAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
